[accounts.deployer]
mnemonic = "nature midnight champion library together afraid diet broccoli purpose entire crumble naive yellow giant actress spirit utility lift solid gravity unit around concert random"
balance = 100000000000000